### ISSUE TITLE
Bower 'bin' folder possible renaming

### ISSUE THREAD

**Issue by ohmatt** [mvindahl/angular-pan-zoom#30]
I was looking to use this library for a production-level webapp, but we have strict filtering in place to not allow "bin" folders for security. We are using grunt to automate building and compiling external libraries through bower, and because of these constraints are having problems with this library. It is definitely possible for us to create a workaround in our Gruntfile as to rename the directory ourselves, but I thought I would suggest it as a fix in general because I have not come across other libraries in bower that use the bin directory for the final code. It seems to be more common that 'src', or 'release' is used.

I can understand not wanting to implement something like this so that it will not break anything for other users of the repository, just thought I would suggest it and see if it might be worth doing to keep consistent with other libraries distributed through bower.

**Comment by askarby** [comment]
I would agree, naming the artifact folder either build, release or dist
seems more appropriate. The name bin usually covers actual executable
javascript files.

What do you think, Martin?
Den 30/01/2015 21.32 skrev "ohmatt" <notifications@github.com>:

**Comment by ohmatt** [comment]
I have created a pull request with the new 'release' folder, but kept the 'bin' folder in tact at the moment, leaving it up to Martin to review and decide if he would like to include these changes. The 'bin' folder should be replaced by the 'release' folder, but I kept it in there to allow Martin to make the decision on keeping or replacing 'bin'.

**Comment by mvindahl** [comment]
Seems like a valid request to me. "Release" is a far more suitable name than "bin".

Also, as you point out, no reason to bother other users unnecessarily so I think we'll live with identical code in both the bin folder and the release folder until we do the next major version bump. I could drop a README file into the bin folder explaining that it is deprecated and that people might as well switch right away.

I think this approach would be the best way to fix the problem and keep everyone happy during the transition.

**Comment by ohmatt** [comment]
Awesome. Thanks for quickly responding to this as well. Are you able to update the bower configuration now as well? I'm not familiar with that process, so I didn't know if that takes time to update or what.

**Comment by mvindahl** [comment]
I'm bumping the version numbers to 1.0.5 in all file headers and in the bower file, I'm just double checking. Once I've committed, I'll add a semver tag in git and bower will pick it up. It's pretty slick.

And happy to be of assistance since you caught me watching silly YouTube videos in the couch anyway :)

**Comment by ohmatt** [comment]
Well, thanks again for the quickness. Enjoy the YouTube videos! :)

**Comment by mvindahl** [comment]
It's now up to 1.0.5 in the bower registry. Happy programming and have a nice weekend!
