### ISSUE TITLE
Chrome: when nesting SVG, text becomes jagged and performance seems degraded

### ISSUE THREAD

**Issue by mvindahl** [mvindahl/angular-pan-zoom#34]
Not sure which versions of Chrome that this applies to but we see this in our project. Even for small amounts of SVG, the text becomes jagged and non-antialiased. For larger amounts of SVG, rendering sometimes stops in mid air and leaves blank areas on the screen.

We don't see it in Safari so it doesn't seem to be a webkit thing.

**Comment by askarby** [comment]
Doesn't this make it a Blink thing, since Chrome uses Blink, and Safari
uses Website?
Den 13/04/2015 14.13 skrev "Martin Vindahl Olsen" <notifications@github.com

**Comment by mvindahl** [comment]
Might very well be ...

Anyway, I found a fix. Seems like Chrome handles the zoom style (http://caniuse.com/#search=zoom) nicely but doesn't always handle the transform style (http://caniuse.com/#search=transform) very well. IE, on the other hand, does not support the zoom style at all.

Let me reveal that the fix involves browser vendor sniffing ... :-P
