### ISSUE TITLE
Pan stops working after mousewheel zoom

### ISSUE THREAD

**Issue by xingped** [mvindahl/angular-pan-zoom#35]
In your demo, I can pan around just fine, but once I use the mousewheel to zoom in and out, the pan stops working. I will be able to pan again if I click one of the specified zoom buttons, but it will again stop working if I mousewheel zoom again.

**Comment by mvindahl** [comment]
Hi,
You're absolutely right. The mousewheel zoom is also broken; the zoom doesn't happen at the point that the mouse points at.
These are serious issues and I'll be looking into them ASAP.
Cheers,
/Martin

**Comment by mvindahl** [comment]
Turns out that it was caused by an API change in Hamster.JS. I've fixed the way we deal with HamsterJS and released the fix as v1.0.7 on bower.

@xingped, thanks for reporting the issue!

Cheers,
/Martin

Ref: https://github.com/monospaced/hamster.js/commit/e6da3e67519a8ad2f30899f1986dd8402860524a
