### ISSUE TITLE
How about min zoom

### ISSUE THREAD

**Issue by nyambayar0613** [mvindahl/angular-pan-zoom#43]
Thank for nice directive.
how to set min zoom ?

**Comment by nyambayar0613** [comment]
handled with neutralZoomLevel thank you

**Comment by nyambayar0613** [comment]
handled with neutralZoomLevel thank you

**Comment by nyambayar0613** [comment]
handled with neutralZoomLevel thank you

**Comment by nyambayar0613** [comment]
handled with neutralZoomLevel thank you

**Comment by mvindahl** [comment]
You're welcome. Hope that you find the directive to be useful :)
