### ISSUE TITLE
TypeError: panElement.get is not a function at new controller (panzoom.js:23)

### ISSUE THREAD

**Issue by jidan70** [mvindahl/angular-pan-zoom#44]
Hi i got this error just using the directive as it said in your first example.

**Comment by jidan70** [comment]
It's good in fact i put jquery.js before angular.js and now it's good.

**Comment by mvindahl** [comment]
Great :) .. glad that you made it work and I appreciate that you took the time to give feedback on the cause of the problem.

Happy coding!
