### ISSUE TITLE
<!DOCTYPE html> prevents pan to function at all

### ISSUE THREAD

**Issue by ReyReyesR** [mvindahl/angular-pan-zoom#47]
Hello, I was loading your script on my project and could zoom on images but only in the x=0 y=0 coordinates, panning and dragging the image was impossible.
![zoom-no-drag1](https://cloud.githubusercontent.com/assets/6729128/12484690/a4bacace-c02d-11e5-92ed-56e423be60ec.jpg)
![zoom-no-drag2](https://cloud.githubusercontent.com/assets/6729128/12484691/a4bff364-c02d-11e5-8b29-683806b18dba.jpg)

After several hours of testing and loading the exact same code in my index.html from the demo, I came to the conclusion that the <!DOCTYPE html> tag was preventing the drag and pan directive to work at all, removing it seemed to fix the problem.

I don't know if this is a known bug or this limitation is on purpose since  I couldn't find info about it anywhere.

Thanks for your time.

**Comment by mvindahl** [comment]
Hello Rey,
This is a bit surprising and it may be a bug. I'll have a look at reproducing it when time permits, probably in the upcoming weekend.
Best regards,
/Martin

**Comment by cperezvinsite** [comment]
Same here !!

**Comment by mvindahl** [comment]
First off, please accept my apologies for not having looked into this until now even though I promised to do so.

Anyway, this was a bone fide bug and it has been fixed now. Consequently, the version number has been incremented to 1.0.16 in both npm and bower.

Again, apologies for my tardiness.
