### ISSUE TITLE
Print the panzoom

### ISSUE THREAD

**Issue by cperezvinsite** [mvindahl/angular-pan-zoom#48]
Hi, there is a way to print the panzoom element? the thing is i have an ng-repeat inside the panzoom, then when I try to print, everithing became a mess, the div doesn't contain correctly the inside images

thanks

**Comment by mvindahl** [comment]
Hello @cperezvinsite,

No, I haven't really considered the issue of printing, and I believe it is largely orthogonal to the needs which the pan zoom directive aims to solve. In other words, I don't foresee that special support for printing will become part of angular-pan-zoom.

More broadly speaking, my personal experience with printing web content of any kind over the years has been largely disappointing. Usually the elements end up more or less in a mess and page breaks tend to occur in the most inconvenient of places.

There are libraries out there which promise to be able to print selected HTML elements, e.g. https://www.npmjs.com/package/print-html-element. I haven't tested any of this so I don't know if they play well with angular-pan-zoom.

Sorry that I can't be of more help, but I'll close this as an issue.
