### ISSUE TITLE
two finger touch on mac trackpad causes zoom out

### ISSUE THREAD

**Issue by john-bai** [mvindahl/angular-pan-zoom#51]
When I place my two fingers on the mac trackpad and prepare to start scrolling, a zoom out occurs.

I debugged the issue and noticed the wheel event is triggered when I place my fingers on the trackpad. A sign variable is calculated to NaN (var sign = $deltaY / Math.abs($deltaY);) since the deltaY is 0. We need to ensure we only zoom out if sign is a positive number. NaN should not trigger a zoom.

**Comment by john-bai** [comment]
PR #52 provides a fix.

**Comment by mvindahl** [comment]
Hello John, sorry for not responding more promptly but I was camping in a place with very limited internet access. I'll have a look at the code today and I expect to approve the PR. Once approved, I'll do a version bump in bower and npm. Thanks for your contribution, it's very appreciated! :)
Cheers, /Martin

**Comment by mvindahl** [comment]
Thanks. Was a small change so easy approval. Bumped to 1.0.18 in bower and npm. Once again, thanks for chipping in! :)

**Comment by john-bai** [comment]
@mvindahl My pleasure! I'll close this issue now that the PR is in.
